variables:
  repositoryQuizMaker: 'jannemattila/quizmaker'
  repositoryQuizSim: 'jannemattila/quizsim'

trigger:
- master
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repositoryQuizMaker)
        command: 'buildAndPush'
        Dockerfile: 'src/QuizMaker/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest    

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repositoryQuizSim)
        command: 'buildAndPush'
        Dockerfile: 'src/QuizUserSimulator/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: deploy'
      inputs:
        PathtoPublish: deploy
        ArtifactName: deploy

- template: azure-pipelines-deploy.yml
  parameters:
    environtName: 'Dev'
    appName: 'Quiz DEV'
    tenantName: $(TenantName)
    resourceGroupName: 'quizmaker-dev-rg'
    dockerImageTag: '$(Build.BuildNumber)'
