variables:
  imageName: 'jannemattila/quizmaker:$(Build.BuildNumber)'

trigger:
- master
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: Docker@1
      displayName: 'Build an image'
      inputs:
        imageName: $(imageName)
        includeLatestTag: true
    
    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: DockerHub
        command: 'Push an image'
        imageName: $(imageName)
        includeSourceTags: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: deploy'
      inputs:
        PathtoPublish: deploy
        ArtifactName: deploy

- template: azure-pipelines-deploy.yml
  parameters:
    environtName: 'Dev'
    appName: 'Quiz DEV'
    tenantName: $(TenantName)
    resourceGroupName: 'quizmaker-dev-rg'
    dockerImageTag: '$(Build.BuildNumber)'
