apiVersion: v1
kind: Namespace
metadata:
  name: quiz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizsim
  namespace: quiz
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: quizsim
    spec:
      containers:
      - image: quizsim:latest
        imagePullPolicy: IfNotPresent
        name: quizsim
        env:
          - name: Endpoint
            value: "https://yourserver/QuizHub"
