name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set Node.js 16.x
      uses: actions/setup-node@master
      with:
        version: 16.x

    - name: npm install
      run: |
        cd src/QuizMaker
        npm install

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202

    - name: Build with dotnet
      run: dotnet build --configuration Release
